# Generated by Django 4.0.6 on 2022-07-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('accuracy', models.IntegerField()),
                ('power', models.IntegerField()),
                ('damage_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('double_damage_from', models.JSONField(default=dict)),
                ('double_damage_to', models.JSONField(default=dict)),
                ('half_damage_from', models.JSONField(default=dict)),
                ('half_damage_to', models.JSONField(default=dict)),
                ('no_damage_from', models.JSONField(default=dict)),
                ('no_damage_to', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('sprite', models.ImageField(upload_to='')),
                ('moves', models.JSONField(default=dict)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('type_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type1', to='pokemon_data.type')),
                ('type_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type2', to='pokemon_data.type')),
            ],
        ),
    ]
