# Generated by Django 4.0.6 on 2022-07-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='accuracy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='power',
            field=models.IntegerField(null=True),
        ),
    ]
