# Generated by Django 4.0.6 on 2022-07-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_data', '0002_alter_move_accuracy_alter_move_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='moves',
            new_name='move_set',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='move',
            field=models.CharField(default='pound', max_length=50),
        ),
    ]
