# Generated by Django 4.0.6 on 2022-07-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_data', '0004_alter_pokemon_height_alter_pokemon_sprite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='special_defense',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type2', to='pokemon_data.type'),
        ),
    ]
