# Generated by Django 4.0.6 on 2022-07-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_data', '0005_pokemon_special_defense_alter_pokemon_type_2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemon',
            new_name='ModelsPokemon',
        ),
    ]
