# Generated by Django 4.0.6 on 2022-07-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_data', '0006_rename_pokemon_modelspokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelspokemon',
            name='sprite',
            field=models.ImageField(upload_to='pokemon_data/static/pokemon'),
        ),
    ]
